# Generated by Django 4.1.2 on 2022-11-24 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='number_society',
            new_name='Flat_number_society',
        ),
    ]
