# Generated by Django 4.1.2 on 2023-05-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_orderitems_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='Order',
            new_name='main_order',
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
