# Generated by Django 4.1.2 on 2023-05-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_order_asd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='asd',
        ),
    ]
