# Generated by Django 4.1.2 on 2023-05-18 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_number_society_address_flat_number_society'),
        ('product', '0015_remove_order_asd'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Address',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='user.address'),
            preserve_default=False,
        ),
    ]
