# Generated by Django 4.1.2 on 2023-05-18 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
